#!/usr/bin/env python3
"""Generate a proxy-DLL export list from what the game exe imports from a DLL.

    python3 tools/gen_proxy.py --exe "$GAME_DIR/F.E.A.R. 3.exe" --dll fmodex.dll \
        --def fmodex.def --inc src/proxy_exports.inc --prefix fmod

Emits a .def aliasing every imported name (MSVC-mangled names included) onto a
plain C symbol <prefix>_<n>, and an X-macro include listing (index, exported
name) for src/proxy.cpp, which builds one jmp thunk per entry. Pure stdlib.
"""
import argparse, struct


def imports_of(exe_path, dll_name):
    d = open(exe_path, "rb").read()
    pe = struct.unpack_from("<I", d, 0x3C)[0]
    nsec = struct.unpack_from("<H", d, pe + 6)[0]
    opt = pe + 24
    opt_sz = struct.unpack_from("<H", d, pe + 20)[0]
    secs = []
    for i in range(nsec):
        o = opt + opt_sz + i * 40
        vsz, va, rsz, rptr = struct.unpack_from("<IIII", d, o + 8)
        secs.append((va, max(vsz, rsz), rptr))

    def rva2off(rva):
        for va, sz, rptr in secs:
            if va <= rva < va + sz:
                return rptr + (rva - va)
        raise ValueError(f"rva {rva:#x} not in any section")

    def cstr(off):
        e = d.find(b"\0", off)
        return d[off:e].decode("ascii")

    imp_rva = struct.unpack_from("<I", d, opt + 104)[0]  # DataDirectory[1] (imports), PE32
    o = rva2off(imp_rva)
    names = []
    while True:
        oft, _, _, name_rva, ft = struct.unpack_from("<IIIII", d, o)
        if not name_rva:
            break
        if cstr(rva2off(name_rva)).lower() == dll_name.lower():
            t = rva2off(oft or ft)
            while True:
                thunk = struct.unpack_from("<I", d, t)[0]
                if not thunk:
                    break
                if thunk & 0x80000000:
                    names.append(f"#{thunk & 0xFFFF}")  # by ordinal (not supported by the .def alias)
                else:
                    names.append(cstr(rva2off(thunk) + 2))
                t += 4
        o += 20
    return names


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--exe", required=True)
    ap.add_argument("--dll", required=True)
    ap.add_argument("--def", dest="def_path", required=True)
    ap.add_argument("--inc", required=True)
    ap.add_argument("--prefix", default="proxy")
    a = ap.parse_args()
    names = imports_of(a.exe, a.dll)
    if not names:
        raise SystemExit(f"{a.dll}: no imports found in {a.exe}")
    ordinals = [n for n in names if n.startswith("#")]
    if ordinals:
        raise SystemExit(f"{a.dll}: ordinal imports are not supported: {ordinals}")
    lib = a.dll.rsplit(".", 1)[0]
    with open(a.def_path, "w") as f:
        f.write(f"; Generated by tools/gen_proxy.py from the game's import table - do not edit by hand.\n")
        f.write(f"; F.E.A.R. 3 imports these {len(names)} symbols from {a.dll}; each is aliased onto a\n")
        f.write(f"; jmp thunk in src/proxy.cpp that jumps into {lib}_orig.dll.\n")
        f.write(f"LIBRARY {lib}\nEXPORTS\n")
        for i, n in enumerate(names):
            f.write(f"    {n} = {a.prefix}_{i}\n")
    with open(a.inc, "w") as f:
        f.write("// Generated by tools/gen_proxy.py - do not edit by hand.\n")
        f.write(f"// X(index, exported name) for every symbol the exe imports from {a.dll}.\n")
        f.write("#define PROXY_EXPORTS(X) \\\n")
        for i, n in enumerate(names):
            f.write(f'  X({i}, "{n}") \\\n')
        f.write("\n")
        f.write(f"#define PROXY_EXPORT_COUNT {len(names)}\n")
    print(f"{a.dll}: {len(names)} exports -> {a.def_path}, {a.inc}")


if __name__ == "__main__":
    main()
